### ISSUE TITLE
Add support for linux builds

### ISSUE THREAD

**Issue by koga73** [AngaBlue/exe#5]
It would be great if this package offered support for linux executables

**Comment by AngaBlue** [comment]
Hi @koga73 ,
This is an interesting suggestion and something that I think would be worthwhile for this project.  I will have to investigate how modifying the output executable file from pkg works with linux.  I must admit it has been quite a while since I last used a linux desktop environment but if you're able to shed some light on the finer details here that would be much appreciated.

**Comment by koga73** [comment]
After doing a little research it seems that ELF executables on Linux don't support icons but they do perhaps support a version and some other properties? I'm not super familiar with the format. I did however find this which is a "Desktop Entry" file that could be easily generated.
https://specifications.freedesktop.org/desktop-entry-spec/latest/apa.html

**Comment by AngaBlue** [comment]
Hi @koga73 , after doing some more research, I don't plan on supporting ELF executables with this project as it seems that most of key aims of this project (bringing icons and metadata to Windows exectuables), would not apply to Linux executables.  Thank you for the thought though!
